# Generated by Django 5.0.9 on 2024-10-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('MC', 'Main Course'), ('DE', 'Dessert'), ('SA', 'Salad'), ('DR', 'Drink')], default='MC', max_length=2),
        ),
    ]
