# Generated by Django 5.0.9 on 2024-10-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_recipe'),
        ('recipe', '0004_post_ingredients_post_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='images.image'),
        ),
    ]
