# Generated by Django 5.0.9 on 2024-10-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes_and_more'),
        ('recipe', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe.post'),
        ),
    ]
