# Generated by Django 5.0.9 on 2024-11-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
    ]
