# Generated by Django 5.0.9 on 2024-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='No ingredients specified'),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(default='No instructions specified'),
        ),
    ]
