# Generated by Django 5.1.1 on 2024-09-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rating_recipe_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='blog.comment'),
        ),
    ]
