# Generated by Django 5.0.9 on 2024-10-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_recipecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipecomment',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeComment',
        ),
    ]
